# Generated by Django 4.1.4 on 2023-01-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_data', '0002_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=250)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
