# Generated by Django 4.1.4 on 2023-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_data', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('mens', 'mens'), ('ladies', 'ladies'), ('children', 'children'), ('other', 'other')], default='other', max_length=10)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
            ],
        ),
    ]
